In [2]:
import pandas as pd
import numpy as np

# Fake dataset yaratamiz
np.random.seed(42)
ismlar = ["Ali", "Vali", "Hasan", "Husan", "Aziz", "Bek", "Jasur", "Kamol", "Ibrohim", "Shoxrux", 
          "Dilshod", "Rustam", "Farrux", "Shavkat", "Madina", "Zuhra", "Gulnoza", "Umida", "Shahnoza", "Lola"]

yoshlar = np.random.randint(22, 45, size=20)
maoshlar = np.random.randint(4000, 10000, size=20)
shaharlar = ["Toshkent", "Samarqand", "Buxoro", "Farg‘ona", "Andijon", "Namangan", "Xorazm", "Qashqadaryo", "Surxondaryo", "Navoiy"]

# DataFrame yaratamiz
df = pd.DataFrame({
    "Ism": ismlar,
    "Yosh": yoshlar,
    "Maosh": maoshlar,
    "Shahar": np.random.choice(shaharlar, size=20)
})

print(df.head(10))  # Dastlabki 10 qatorni ko‘rsatish

       Ism  Yosh  Maosh       Shahar
0      Ali    28   6433       Xorazm
1     Vali    41   9311     Farg‘ona
2    Hasan    36   9051  Surxondaryo
3    Husan    32   5184       Buxoro
4     Aziz    29   8555      Andijon
5      Bek    42   7385       Buxoro
6    Jasur    28   8117       Xorazm
7    Kamol    40   8843      Andijon
8  Ibrohim    44   6904  Surxondaryo
9  Shoxrux    32   4474       Xorazm

In [3]:
df['Tajriba'] = df['Yosh']-22
df

         Ism  Yosh  Maosh       Shahar  Tajriba
0        Ali    28   6433       Xorazm        6
1       Vali    41   9311     Farg‘ona       19
2      Hasan    36   9051  Surxondaryo       14
3      Husan    32   5184       Buxoro       10
4       Aziz    29   8555      Andijon        7
5        Bek    42   7385       Buxoro       20
6      Jasur    28   8117       Xorazm        6
7      Kamol    40   8843      Andijon       18
8    Ibrohim    44   6904  Surxondaryo       22
9    Shoxrux    32   4474       Xorazm       10
10   Dilshod    32   5082    Samarqand       10
11    Rustam    42   6558     Farg‘ona       20
12    Farrux    25   6047  Surxondaryo        3
13   Shavkat    29   6747    Samarqand        7
14    Madina    24   4975       Navoiy        2
15     Zuhra    43   5806  Surxondaryo       21
16   Gulnoza    42   4189       Navoiy       20
17     Umida    23   6734      Andijon        1
18  Shahnoza    33   7005    Samarqand       11
19      Lola    27   8658     Farg‘ona        5

In [5]:
df['Kategoriya'] = df['Maosh'].apply(lambda x: "Yetakchi" if x > 7000 else "Xodim")
df

         Ism  Yosh  Maosh       Shahar  Tajriba Kategoriya
0        Ali    28   6433       Xorazm        6      Xodim
1       Vali    41   9311     Farg‘ona       19   Yetakchi
2      Hasan    36   9051  Surxondaryo       14   Yetakchi
3      Husan    32   5184       Buxoro       10      Xodim
4       Aziz    29   8555      Andijon        7   Yetakchi
5        Bek    42   7385       Buxoro       20   Yetakchi
6      Jasur    28   8117       Xorazm        6   Yetakchi
7      Kamol    40   8843      Andijon       18   Yetakchi
8    Ibrohim    44   6904  Surxondaryo       22      Xodim
9    Shoxrux    32   4474       Xorazm       10      Xodim
10   Dilshod    32   5082    Samarqand       10      Xodim
11    Rustam    42   6558     Farg‘ona       20      Xodim
12    Farrux    25   6047  Surxondaryo        3      Xodim
13   Shavkat    29   6747    Samarqand        7      Xodim
14    Madina    24   4975       Navoiy        2      Xodim
15     Zuhra    43   5806  Surxondaryo       21      Xodim
16   Gulnoza    42   4189       Navoiy       20      Xodim
17     Umida    23   6734      Andijon        1      Xodim
18  Shahnoza    33   7005    Samarqand       11   Yetakchi
19      Lola    27   8658     Farg‘ona        5   Yetakchi

In [11]:
df['BeshinchiHarf'] = df['Ism'].apply(lambda x: x[4] if len(x) >= 5 else "")
df

         Ism  Yosh  Maosh       Shahar  Tajriba Kategoriya BeshinchiHarf
0        Ali    28   6433       Xorazm        6      Xodim
1       Vali    41   9311     Farg‘ona       19   Yetakchi
2      Hasan    36   9051  Surxondaryo       14   Yetakchi             n
3      Husan    32   5184       Buxoro       10      Xodim             n
4       Aziz    29   8555      Andijon        7   Yetakchi
5        Bek    42   7385       Buxoro       20   Yetakchi
6      Jasur    28   8117       Xorazm        6   Yetakchi             r
7      Kamol    40   8843      Andijon       18   Yetakchi             l
8    Ibrohim    44   6904  Surxondaryo       22      Xodim             h
9    Shoxrux    32   4474       Xorazm       10      Xodim             r
10   Dilshod    32   5082    Samarqand       10      Xodim             h
11    Rustam    42   6558     Farg‘ona       20      Xodim             a
12    Farrux    25   6047  Surxondaryo        3      Xodim             u
13   Shavkat    29   6747    Samarqand        7      Xodim             k
14    Madina    24   4975       Navoiy        2      Xodim             n
15     Zuhra    43   5806  Surxondaryo       21      Xodim             a
16   Gulnoza    42   4189       Navoiy       20      Xodim             o
17     Umida    23   6734      Andijon        1      Xodim             a
18  Shahnoza    33   7005    Samarqand       11   Yetakchi             n
19      Lola    27   8658     Farg‘ona        5   Yetakchi

In [13]:
group_kategoriya = df.groupby('Kategoriya')['Maosh'].count()
group_kategoriya

Kategoriya
Xodim       12
Yetakchi     8
Name: Maosh, dtype: int64