In [7]:
import pandas as pd

df = pd.DataFrame({
    'Ism': ['Ali', 'Vali', 'Hasan', 'Husan', 'Aziz'],
    'Shahar': ['Toshkent', 'Samarqand', 'Toshkent', 'Farg‘ona', 'Samarqand'],
    'Yosh': [25, 30, 28, 35, 29]
})

print(df)

guruhlangan = df.groupby('Shahar')['Yosh'].mean()
print(guruhlangan)

     Ism     Shahar  Yosh
0    Ali   Toshkent    25
1   Vali  Samarqand    30
2  Hasan   Toshkent    28
3  Husan   Farg‘ona    35
4   Aziz  Samarqand    29
Shahar
Farg‘ona     35.0
Samarqand    29.5
Toshkent     26.5
Name: Yosh, dtype: float64

In [9]:
natija = df.groupby('Shahar')['Yosh'].agg(['min', 'max', 'mean'])
print(natija)

           min  max  mean
Shahar
Farg‘ona    35   35  35.0
Samarqand   29   30  29.5
Toshkent    25   28  26.5

In [11]:
pivot = df.pivot_table(values='Yosh', index='Shahar', aggfunc=['mean', 'count'])
print(pivot)

           mean count
           Yosh  Yosh
Shahar
Farg‘ona   35.0     1
Samarqand  29.5     2
Toshkent   26.5     2

In [13]:
df['Guruh_o‘rtacha_yoshi'] = df.groupby('Shahar')['Yosh'].transform('mean')
print(df)

     Ism     Shahar  Yosh  Guruh_o‘rtacha_yoshi
0    Ali   Toshkent    25                  26.5
1   Vali  Samarqand    30                  29.5
2  Hasan   Toshkent    28                  26.5
3  Husan   Farg‘ona    35                  35.0
4   Aziz  Samarqand    29                  29.5

In [18]:
df = pd.DataFrame({
    'Ism': ['Ali', 'Vali', 'Hasan', 'Husan', 'Aziz'],
    'Kasb': ['Dasturchi', 'Dizayner', 'Muhandis', 'Dasturchi', 'Dizayner'],
    'Yosh': [25, 30, 28, 35, 29],
    'Maosh': [2500, 3000, 2800, 3500, 2900]
})

df

     Ism       Kasb  Yosh  Maosh
0    Ali  Dasturchi    25   2500
1   Vali   Dizayner    30   3000
2  Hasan   Muhandis    28   2800
3  Husan  Dasturchi    35   3500
4   Aziz   Dizayner    29   2900

In [20]:
group_df = df.groupby('Kasb')['Maosh'].mean()
group_df

Kasb
Dasturchi    3000.0
Dizayner     2950.0
Muhandis     2800.0
Name: Maosh, dtype: float64

In [23]:
agg_df = df.groupby('Kasb')['Maosh'].agg(['min', 'max', 'mean'])
agg_df

            min   max    mean
Kasb
Dasturchi  2500  3500  3000.0
Dizayner   2900  3000  2950.0
Muhandis   2800  2800  2800.0

In [27]:
df.loc[(df['Kasb'] == 'Dasturchi') & (df['Yosh'] >= 30), 'Maosh'] *= 1.1
df

C:\Users\wecan\AppData\Local\Temp\ipykernel_2400\2271190872.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[3850.]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df['Kasb'] == 'Dasturchi') & (df['Yosh'] >= 30), 'Maosh'] *= 1.1

     Ism       Kasb  Yosh   Maosh
0    Ali  Dasturchi    25  2500.0
1   Vali   Dizayner    30  3000.0
2  Hasan   Muhandis    28  2800.0
3  Husan  Dasturchi    35  3850.0
4   Aziz   Dizayner    29  2900.0

In [29]:
import pandas as pd

data = {
    "Ism": ["Ali", "Vali", "Hasan", "Husan", "Aziz"],
    "Kasb": ["Dasturchi", "Dizayner", "Muhandis", "Dasturchi", "Dizayner"],
    "Maosh": [5000, 4500, 5500, 6000, 4700],
    "Yosh": [25, 30, 28, 35, 29]
}

df = pd.DataFrame(data)

In [30]:
df['Yosh toifa'] = df['Yosh'].apply(lambda yosh: "Yosh" if yosh < 28 else "O‘rta yosh" if yosh < 35 else "Katta yosh")

df

     Ism       Kasb  Maosh  Yosh  Yosh toifa
0    Ali  Dasturchi   5000    25        Yosh
1   Vali   Dizayner   4500    30  O‘rta yosh
2  Hasan   Muhandis   5500    28  O‘rta yosh
3  Husan  Dasturchi   6000    35  Katta yosh
4   Aziz   Dizayner   4700    29  O‘rta yosh

In [49]:
import pandas as pd

df1 = pd.DataFrame({
    "ID": [1, 2, 3, 4],
    "Ism": ["Ali", "Vali", "Hasan", "Husan"],
    "Yosh": [25, 30, 28, 35]
})

df2 = pd.DataFrame({
    "ID": [3, 4, 5, 6],
    "Kasb": ["Muhandis", "Dasturchi", "Dizayner", "O‘qituvchi"],
    "Maosh": [5500, 6000, 4700, 4000]
})


all= pd.merge(df1, df2, on='ID', how='outer')
all

   ID    Ism  Yosh        Kasb   Maosh
0   1    Ali  25.0         NaN     NaN
1   2   Vali  30.0         NaN     NaN
2   3  Hasan  28.0    Muhandis  5500.0
3   4  Husan  35.0   Dasturchi  6000.0
4   5    NaN   NaN    Dizayner  4700.0
5   6    NaN   NaN  O‘qituvchi  4000.0

In [52]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Ism": ["Ali", "Vali", "Hasan", "Husan", "Aziz"],
    "Kasb": ["Dasturchi", "Dizayner", np.nan, "Dasturchi", "Dizayner"],
    "Maosh": [5000, np.nan, 5500, 6000, np.nan]
})

print(df)

     Ism       Kasb   Maosh
0    Ali  Dasturchi  5000.0
1   Vali   Dizayner     NaN
2  Hasan        NaN  5500.0
3  Husan  Dasturchi  6000.0
4   Aziz   Dizayner     NaN